# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ccc40c224df21636d0a344d5417732d2355afd6711e6a26db7aad002a5034d1e4fee47d541e60dd25bbb05a205e441a67b333a68870ab66665df417d23190f6

test:
  secret_key_base: 054107ca8cd84b7e5e374445ef8eecc5e1eae9fd6122b86bbc0a3fcdcefeda5c9d475f647709062f929aa615deda2e93dcc00b103a4baa3a17512f797d6966e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
